### ISSUE TITLE
5/3 Bi-weekly Automation Update

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/analyticsPiplelines#5]
This week's priorities: 

1. Module metrics
- Notifications QC had to be updated again: new newsletter type;  client side email name the same for two different email types and was causing problems 
- PR in with no merge conflicts, ready to go to main
3. Biospecimen Report
- Home Mouthwash tables likely going to be added. Erin will let me know by EOD
- Will submit PR tomorrow morning at the latest, though likely tonight
3. Only if we have time, the Monthly PROMIS Summary Statistics built in the Module Metrics repo

Checklist:
- [x] Notifications QC in Module Metrics **[ran successfully]**
- [x] Weekly Biospecimen Report **[ran successfully with CSV chunks removed]**
- [ ] Monthly PROMIS Summary Statistics **[push till next time]**

**Comment by KELSEYDOWLING7** [comment]
Update: the Biospecimen team wants to add plots and maybe request new tables so we won't have to touch that this week. Just the Module Metrics repo for the Notifications QC and monthly PROMIS summary statistics

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Sorry for all the back and forth! Forgot I hadn't merged the SF hybrid updates so we will need to update the Weekly Biospecimen report. I'll do a PR for that shortly

**Comment by jacobmpeters** [comment]
Thanks, Kelsey. I'm working through this checklist now.

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Notifications QC looks good!

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 The biospecimen report failed with an R error near the end of the script.

<img width="761" alt="Screenshot 2024-05-03 at 3 38 59 PM" src="https://github.com/Analyticsphere/analyticsPiplelines/assets/7967451/26c18c34-266d-4bf0-8b0f-60e261d87994">

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Shoot ok that hasn't changed since last week so I'm not sure why. The variables it's claiming not to have are in the DF and DD. For now is it possible to remove the csv chunks and I'll try running those manually on Monday/work with Jing if the was a DD change?

**Comment by jacobmpeters** [comment]
I'll give that a shot and get back to you. I'm assuming I can just comment out the last two chunks and run it again.

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Right, that's what I'm thinking. Thank you!

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 The biospecimen metrics ran fine without those chunks on Friday.

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters Yes, I was actually just looking at that. Thank you! I'll run the csv code locally
