### ISSUE TITLE
Biweekly Automation Update- 5/17

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/analyticsPiplelines#6]
Hi Jake, these are this list of priorities for this weeks automation. Really 1-4 are the only ones that need to get done, number 5 is just an 'if we have time' addition. I'll be making all PR by the end of the day today.

I'll also be out Monday so I'll give Jing a list of the report and the link for the GCP report status.

1. [X] Weekly Biospecimen report Update **[SUCCESS]**
2. [x] Notification QC (Code failed in GCP this week but no issues running locally in R) **[SUCCESS]**
3. [x] New Weekly PROMIS Completion vs Notifications Report to be posted to Box here:  https://nih.app.box.com/folder/262287498430 **[SUCCESS]**
4. [x] Module 1 Metric QC (Code failed in GCP this week but no issues running locally in R) **[SUCCESS]**
5. [x] New Monthly 3 month QOL Summary Statistics Report to go here: https://nih.app.box.com/folder/251314285484 **[SUCCESS]**
6. [x] Weekly Operations Report- updated table/figure ordering. Completely fine if this is moved to the next automation date but wanted to give you the heads up **[SUCCESS]**

**Comment by jacobmpeters** [comment]
Great, thanks for the priority list!

**Comment by KELSEYDOWLING7** [comment]
Of course! And I emailed Renelle to add you to the new Box folder for the PROMIS Notification report

**Comment by jacobmpeters** [comment]
Ok! Thanks! She'll also need to give this account (AutomationUser_1960507_dBBoRFHiim@boxdevedition.com) viewer/uploader permissions..

**Comment by KELSEYDOWLING7** [comment]
Oh no! Sorry I should've asked you before I emailed. Can you reply all asking for those permissions to be added as well?

**Comment by jacobmpeters** [comment]
I think you did it right! I just saw your email. Sorry!

**Comment by KELSEYDOWLING7** [comment]
Oh, no worries!

**Comment by KELSEYDOWLING7** [comment]
I added the updated Weekly Operations report but I believe I was able to merge it with the main branch myself. https://github.com/Analyticsphere/weekly_ccc_report_gcp_pipeline/pull/49 . This was just a reordering of tables and figures so I don't anticipate issues

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 Is the "3 month QOL Summary Statistics Report" supposed to run every Monday?

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters No that one is monthly, PROMIS Completion vs Notifications Report is weekly

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 Everything ran successfully!!
