### ISSUE TITLE
6/7/24 Automation Update

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [Analyticsphere/analyticsPiplelines#8]
- [x] Operations Report CSV failed- can we look into why and what may need to be fixed? **[success]**
- [x] Biospecimen Report will have a few updates (I will push the PR if Erin approves the chances in time, otherwise that will be moved to the next automation update **[success]**
- [ ] Module 1 general (non-custom) QC has been failing for about a month now. Is this still a saving issue or something else we have to address? Also I was able to talk to Daniel about one issue that's come up a lot and I need to see if number of occurrences for that issue has hiked up again **[diagnosed issue, will fix Monday and trigger then]**

**Comment by KELSEYDOWLING7** [comment]
Ran Operations csv report on Tuesday with no issues locally. 
Made a PR for the Biospecimen report.

I don't know if we'll have time today but I think it would be a good idea to separate out the csv files from the Biospecimen report as we did with the Operations report. There tends to be more issues with those then the rest of the report, and they're going to a different Box folder anyways.

**Comment by jacobmpeters** [comment]
@KELSEYDOWLING7 I ran the Weekly Operations CSVs and received this error right after bigrquery was loaded: 
<img width="846" alt="Screenshot 2024-06-07 at 2 45 55 PM" src="https://github.com/Analyticsphere/analyticsPiplelines/assets/7967451/590a7bba-aa96-4ce4-9d6b-af01b521cd59">

**Comment by jacobmpeters** [comment]
The biospecimen report ended with this R error. Looks like there is a hard-coded file path...

<img width="1192" alt="Screenshot 2024-06-07 at 2 48 05 PM" src="https://github.com/Analyticsphere/analyticsPiplelines/assets/7967451/99e997fe-4241-4af0-b648-90f590f235df">

**Comment by KELSEYDOWLING7** [comment]
@jacobmpeters  Weird, for the operations csv the project is mapped on line 87 and it didn't cause issues locally.  Maybe lines 87&88 should go above the con definition on line 51?

**Comment by KELSEYDOWLING7** [comment]
For the Biospecimens report I completely forgot that yes SF sent us a file that that code references. I'll push that to the Biospecimen repo right now. Sorry about that!

**Comment by jacobmpeters** [comment]
> @KELSEYDOWLING7 I ran the Weekly Operations CSVs and received this error right after bigrquery was loaded: <img alt="Screenshot 2024-06-07 at 2 45 55 PM" width="846" src="https://private-user-images.githubusercontent.com/7967451/337758722-590a7bba-aa96-4ce4-9d6b-af01b521cd59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3OTEzODcsIm5iZiI6MTcxNzc5MTA4NywicGF0aCI6Ii83OTY3NDUxLzMzNzc1ODcyMi01OTBhN2JiYS1hYTk2LTRjZTQtOWQ2Yi1hZjAxYjUyMWNkNTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMjAxMTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ1NWZhOGFiNWNlOWYwZjdlNDlkMzdlZGIwZDMwODFiYTI2YTI2OWRlMDNiZTgxY2QxZTBiMTNmZDMyZDVkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BLNUi5SOaWjd4crxbodF_0j71GgaAF2lVl4-fjCqHkQ">

I'll pull this down and test it locally

**Comment by KELSEYDOWLING7** [comment]
Ok. My local Operations repo just crashed but hopefully moving the project and billing before con solves the issue since project IS defined

**Comment by jacobmpeters** [comment]
The biospecimen report and the operations CSVs ran successfully.

I diagnosed the issue with the Module 1 QC and will work to resolve it Monday. I will trigger it to run in GCP when done.
